version: '3'
services:
  web:
    build: ./devops-test
    command: >
        bash -c "flask db upgrade 
        && flask run --host=0.0.0.0 --port=5000"
    ports:
    - 5000:5000
    volumes:
    - ./devops-test:/testapp
    depends_on:
    - db
    environment:
     DATABASE_URL: postgres://postgres@db/postgres
     USER_NAME: MeMeME
     USER_URL: Http://www.com/
     SQLALCHEMY_TRACK_MODIFICATIONS: "false"
     FLASK_APP: app.py
     FLASK_ENV: development
     FLASK_RUN_PORT: 5000
  db:
    image: postgres:11
